### ISSUE TITLE
Style similar to chase app

### ISSUE THREAD

**Issue by rbankston** [rbankston/budget-buddy-project#3]
Guidance https://www.vangalasso.com/uxdesign/chasebank

**Comment by rbankston** [comment]
Color palette https://pokepalettes.com/#tentacool

**Comment by rbankston** [comment]
https://fonts.google.com/specimen/Shadows+Into+Light?preview.text=Hello%20Paulline%201%20%2B%202%20%2B%203&preview.text_type=custom#standard-styles

Font

**Comment by rbankston** [comment]
![image](https://user-images.githubusercontent.com/130836/182984156-614effe4-2bde-4fde-a40b-c9ce7e3312e9.png)

**Comment by Jacob-Coffey** [comment]
Total budget at the top with the remaining funds available just underneath that. Then we could do the four categories in their own sections below that. MAYBE we can do weekly budget dollar amount in blue, remaining balance available in green, and then the amount spent on each category in red 
![image](https://user-images.githubusercontent.com/106611041/182984771-a9b7eff6-6acf-4603-a958-f468e6bf5470.png)
